/////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
//
// Compile this file using clang++, g++, or 
// Microsoft Visual Studio C++ compiler.
//
// To compile using Clang type:
//    clang++ main.cpp -O3 -sdt=c++17 -o main
//

#include <string>
#include <vector>
#include "student_code_7.h"
#include "test_framework.h"


const char* smallDataset = "small_problem_set_7.in";
const char* largeDataset = "large_problem_set_7.in";

const char*  helpMsg = "Please, indicate which problem set to use.\n\n"
                       "For small problem set, type: ./main small\n"
                       "For large problem set, type: ./main large\n";

const char* strNotice = "##################################\n"
                        "# Do not edit this file!\n"
                        "##################################\n";

constexpr int problem_set_id = 7;

struct ProblemN7: public TestFramework::BasicProblem
{
   std::vector<int> opcodes;
   std::vector<int> ids;
};

int MaxCommonSubtrees(const std::vector<int>& opcodes,
                      const std::vector<int>& ids)
{
   const char* errorMsg = "Problem set is corrupted.";
   TestFramework::ExitIfConditionFails(opcodes.size() == ids.size(), errorMsg);

   int count = opcodes.size();
   std::vector<Node> tree(count);

   for (int i =0; i < count; ++i)
   {
      tree[i].code = static_cast<Code>(opcodes[i]);
      tree[i].id = ids[i];
   } 

   return MaxCommonSubtrees(tree);
}


int main(int argc, char *argv[])
{
   using namespace TestFramework;

   static_assert (GetTestFrameworkVersion () == 7,
      "TestFramework version 7 is required. Please, update test_framework.h.");

   if ((argc != 2) && (argc != 3))
   {
      std::cout << helpMsg;
   }

   std::string firstArg(DefaultProblemSet());

   if (argc >= 2)
   {
      firstArg = argv[1];
   }
   else
   {
      std::cout << "\nUsing the default problem set: " << firstArg;
   }

   ExitIfConditionFails((firstArg == "small") || (firstArg == "large"), "Unknown problem set.");
   bool bSmallDataset = (firstArg == "small");

   std::cout << std::endl << "Problem set #" << problem_set_id << ". ";

   ProblemSetHeader header;
   RecordAdapter<ProblemSetHeader> psAdapter(header);
   AddDefaultProblemSetColumns(psAdapter);

   std::vector<ProblemN7> problems;
   TableAdapter<ProblemN7> prAdapter(problems);
   AddDefaultProblemColumns(prAdapter);

   AddColumn<ProblemN7>(prAdapter, "opcodes", &ProblemN7::opcodes);
   AddColumn<ProblemN7>(prAdapter, "ids", &ProblemN7::ids);

   BasicYamlParser parser(dynamic_cast<ITable*>(&psAdapter),
                          dynamic_cast<ITable*>(&prAdapter));

   const char* inputFilename = bSmallDataset ? smallDataset : largeDataset;
   std::cout << "File: " << inputFilename << ".\n";

   parser.ParseFile(inputFilename, true);
   header.student_name = GetStudentName();
   PreprocessProblemSet(problem_set_id, problems, header);

   for (int i = 0; i < problems.size(); ++i)
   {
      auto& theProblem = problems[i];
      theProblem.student_answer = MaxCommonSubtrees(theProblem.opcodes, theProblem.ids);
   }

   
   ProcessResults(problems, header);

   std::cout << "Don't forget to submit your source code on Canvas.";
   std::cout << "\nRunning time: " << header.time << "ms";
   std::cout << std::endl << std::endl;
   std::cout << std::endl << std::endl;

   if (argc == 3)
   {
      const char * outputFilename = argv[2];
      std::cout << "Generating a report. ";
      std::cout << "The report is saved in file '" << outputFilename << "'.\n";
      TableAdapter<ProblemN7> prOutAdapter(problems);
      AddDefaultProblemColumnsForOutput(prOutAdapter);

      WriteTableToFile(outputFilename, &prOutAdapter, &psAdapter, true, strNotice);
   }

   return 0;
}
